### ISSUE TITLE
Create a "What I did" markdown report ready for a GitHub issue

### ISSUE THREAD

**Issue by Karm** [quarkus-qe/quarkus-startstop#7]
The TS spits out various information, e.g. measurements, logs, maven commands and their parameters used etc.

When you are forming a report, you need to concatenate .csv files, correlate them with maven commands the TS wrote to log etc.

The TS should be able to form a "What I did" markdown report for each test, e.g. :

 - maven command used
 - measurements
 - versions info

**Comment by rsvoboda** [comment]
I like the idea
